#Name of the application
spring.application.name=Location App

# JPA/DB Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Server Configuration
server.port=3001
server.servlet.contextPath=/api

# Security Configuration (1H Token Expiration: 3600000ms)
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=3600000

# Log Configuration
logging.level.root=WARN

# Dev Tools
spring.devtools.restart.enabled=true

# Swagger
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# files
file.upload-dir=files/